### PR TITLE
remove jasnell from TSC and related email lists

### PR DESCRIPTION
**Pull request by Trott**
James has moved to TSC Emeritus for the time being as he focuses on
internal business for his employer.

### CODE REVIEW

**Comment by Trott** [comment]
/ping @mhdawson @rvagg Can one of you merge this and Make It So? (It's the making-it-so part I don't think I have access to...)

**Comment by mhdawson** [comment]
Have been travelling this week.  Will deploy now.

**Comment by mhdawson** [comment]
PR-URL: https://github.com/nodejs/email/pull/131
Reviewed-By: Myles Borins <myles.borins@gmail.com>
Reviewed-By: Anatoli Papirovski <apapirovski@mac.com>
Reviewed-By: Сковорода Никита Андреевич <chalkerx@gmail.com>
Reviewed-By: Michael Dawson <michael_dawson@ca.ibm.com>

**Comment by mhdawson** [comment]
PR-URL: https://github.com/nodejs/email/pull/131
Reviewed-By: Myles Borins <myles.borins@gmail.com>
Reviewed-By: Anatoli Papirovski <apapirovski@mac.com>
Reviewed-By: Сковорода Никита Андреевич <chalkerx@gmail.com>
Reviewed-By: Michael Dawson <michael_dawson@ca.ibm.com>

**Pull request merged**
