### PR TITLE
chore: update aliases to reflect current moderation team membership

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/build @gdams Is the node-slack-bot email address still a thing?

**Review by othiym23 — APPROVED** [review]
:ship: Third verse, same as the first. Thanks, @Trott!

**Comment by rvagg** [comment]
I don't think `node-slack-bot` was ever owned by @nodejs/build and I don't know if it's maintained. Do you want to wait to get that figured out before merging this?

**Comment by Trott** [comment]
> I don't think `node-slack-bot` was ever owned by @nodejs/build and I don't know if it's maintained. Do you want to wait to get that figured out before merging this?

I think we can treat that issue separately. I'd prefer to get the other email addresses updated promptly. Thanks!

**Comment by rvagg** [comment]
deployed

**Pull request merged**
