### PR TITLE
Add Scott González to Inclusivity

### PR DESCRIPTION
**Pull request by scottgonzalez**

### CODE REVIEW

**Comment by nebrius** [comment]
Scott is a new member to the working group, and we're glad to have him! :)

**Comment by scottgonzalez** [comment]
bump

**Comment by Fishrock123** [comment]
Someone needs to actually be able to push this live, cc @nodejs/build

**Comment by nebrius** [comment]
When we take care of this update, can we also roll in #18?

**Comment by nebrius** [comment]
Bump. @Fishrock123 @nodejs/build can we try and get this PR and #18 deployed soon?

**Comment by jbergstroem** [comment]
Added and pushed. Please test so it works correctly (first time I'm running the updater).

**Comment by scottgonzalez** [comment]
This is working for me. Thanks @jbergstroem.

**Pull request merged**
