### PR TITLE
Add Community Committee list

### PR DESCRIPTION
**Pull request by hackygolucky**
Only those who said they were okay with publish in the repo issue are listed.

### CODE REVIEW

**Comment by MylesBorins** [comment]
It looks like some emails are missing from that list

@nodejs/tsc @nodejs/build  do we need to do anything more than this to add an alias?

**Comment by mhdawson** [comment]
@MylesBorins I'm not 100% sure but I think this is all we need.  I'd suggest we land/test to make sure.

**Comment by MylesBorins** [comment]
landed + sent out test email

**Comment by MylesBorins** [comment]
oh no
screen shot 2017-08-15 at 4 09 05 pm

**Comment by mhdawson** [comment]
Lets make sure other addresses are not messed up in case we need to revert.

**Comment by mhdawson** [comment]
ok email to a different list that I'm on worked ok so at least the others are still ok.  So now to figure out what else needs to happen to enable the list.

**Comment by mhdawson** [comment]
@jbergstroem, @rvagg what else do we need to do to get the alias enabled ?

**Comment by rvagg** [comment]
@mhdawson can I assume from your test email to build@ that you figured out how to get it working yourself?

**Comment by mhdawson** [comment]
@rvagg no, just that we had not broken the others.

The question we have is whether anything other than making this change should be necessary or not.  If the answer is yes, then what so we can do that.  If the answer is no, then we can look closer at the json added to try to figure out why its not working.

**Comment by rvagg** [comment]
@mhdawson added more instructions in #47. Let me know if that makes sense and if you can get it to work with that. Should be a straightforward update from then on, `credentials.json` is in `.gitignore` so you can just keep your local copy in place.

**Comment by mhdawson** [comment]
Thanks will follow those instructions and add approval to PR if all goes well.

**Comment by mhdawson** [comment]
Followed instructions and sent out test email.  Will see if it goes through now.

**Comment by mhdawson** [comment]
Seems like it was good once update was run.

**Pull request merged**
