### PR TITLE
Add joyee to zoom message list

### PR DESCRIPTION
**Pull request by joyeecheung**

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Comment by joyeecheung** [comment]
Can I just merge this?

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
@joyeecheung just merging won't be enough as it needs to be deployed. For that reason we usually ask that one of the people can deploy do the landing, otherwise they may not know its needed.

**Comment by mhdawson** [comment]
deployed

**Pull request merged**
