### PR TITLE
Update CommComm Alias

### PR DESCRIPTION
**Pull request by bnb**
Adds two new members, removes one emeritus.

### CODE REVIEW

**Comment by bnb** [comment]
cc @nodejs/community-committee

**Comment by mhdawson** [comment]
Going to land in order to avoid delays in people getting emails.

**Comment by mhdawson** [comment]
Landed as 8b99a0125858bb14e0232f0a9ea9856731ec8d44

**Comment by WaleedAshraf** [comment]
@Trott Fixed sorting here: https://github.com/nodejs/email/pull/101

**Pull request closed without merging**
