### PR TITLE
Add download-validation-alert

### PR DESCRIPTION
**Pull request by mhdawson**
Add alias for notification of when the download
validation job fails
https://ci.nodejs.org/view/Node.js%20Daily/job/validate-downloads/

Started with just my email.  Have  asked release/build team who else should be added and will update PR once I get responses.

### CODE REVIEW

**Comment by gibfahn** [comment]
I like the idea, but maybe something more general would be good (we will hopefully add more validation going forward). Might `release-validation-alert` be better?

**Comment by mhdawson** [comment]
changes to more general name as suggested

**Comment by refack** [comment]
Isn't https://www.dynatrace.com/ a member of the foundation? that's what they do...

**Comment by mhdawson** [comment]
@refack not sure what your suggestion is.  We already added a job to check downloads this PR is simply to capture who will get notified when the job fails.  I was hoping we'd have more people volunteering.

**Comment by refack** [comment]
> @refack not sure what your suggestion is. We already added a job to check downloads this PR is simply to capture who will get notified when the job fails. I was hoping we'd have more people volunteering.

Probably not for this task, but for future notification and propagation, I was just thinking that they might be a good service to use, and they have an easy to use opt-in/opt-out mechanism.

**Comment by mhdawson** [comment]
@refack  k got it. Will land this.

**Comment by mhdawson** [comment]
landed as 7ba90f182a0da9dc0829f276c22623e0d04c802e

**Pull request closed without merging**
