### PR TITLE
doc: remove user-feedback email

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Review by BethGriggs — APPROVED** [review]

**Comment by richardlau** [comment]
Has the nodejs.org variant that redirected to this one (https://github.com/nodejs/user-feedback/issues/12#issuecomment-350054599) been removed, or is that something else that needs to also be done?

**Review by Trott — APPROVED** [review]

**Comment by mhdawson** [comment]
@brianwarner  can you handle the part on the node.js email side?

**Comment by mhdawson** [comment]
@brianwarner  ping

**Comment by brianwarner** [comment]
I'm sorry, I'm not sure what's needed here? Do you want user-feedback@nodejs.org deleted entirely?

**Comment by mhdawson** [comment]
@brianwarner 

> Do you want [user-feedback@nodejs.org](mailto:user-feedback@nodejs.org) deleted entirely?

YES please

**Comment by brianwarner** [comment]
You got it. This is done now.

**Pull request merged**
