### PR TITLE
Add inclusivity@ for inclusivity WG

### LINKED ISSUE #9: inclusivity reporting email
hello-

i would like `inclusivity@nodejs.com` for reporting inclusivity specific incidents. thanks!

it should forward to a list that includes:
- ashley williams (ashley666ashley@gmail.com)
- julie pagano (julie.pagano@gmail.com)
- beau gunderson (beau@beaugunderson.com)
- nathan zadoks (nathan@nathan7.eu)
- bryan hughes (bryan@theoreticalideations.com)
- forrest norvell (forrest@npmjs.com)
- jona hugger (jona@jona.io)
- sakthipriyan vairamani (thechargingvolcano@gmail.com)
- rich trott (rtrott@gmail.com)
- kat marachan (node@sykosomatic.org)

### PR DESCRIPTION
**Pull request by beaugunderson**
Per @jasnell's suggestion to open a PR that adds the alias. :)

cc: @ashleygwilliams, @sup

Closes #9.

### CODE REVIEW

**Comment by Fishrock123** [comment]
LGTM, @nodejs/tsc?

This stuff works automagically right?

**Comment by Starefossen** [comment]
@Fishrock123 If I recall correctly Rod has to run a script before changes go live. Would be nice to have this fully automated though!

**Comment by jbergstroem** [comment]
Yes I reckon we need to [push this](https://github.com/nodejs/email/blob/master/update/update.js) against the mailgun api.

@rvagg perhaps add the credentials to our infra group?

**Comment by rvagg** [comment]
Lest anyone think I'm holding on to this for myself, the API key is accessible to anyone with access to the NF Rackspace account so it can be updated by any of the build/infra team. For clarification and detailed instructions on how to use it with this repo I've just updated the `build/infra/admin_logins.md` document in the secrets repo.

**Comment by jbergstroem** [comment]
@rvagg: Ah. I can look at pushing it later today.

**Comment by rvagg** [comment]
@jbergstroem nothing to push, this is not merged yet

**Comment by jbergstroem** [comment]
@rvagg sorry; poor language. What I meant was that I can look at the scripts that pushes to get familiarised.

**Comment by ashleygwilliams** [comment]
hello! looks like this came up in the TSC meeting yesterday. could you give us an update @Fishrock123 @jasnell?

**Comment by jasnell** [comment]
Ah, yes, there does not seem to be any objection so we'll get this landed.
After that it's a matter of running some script that actually creates the
alias. I think @rvagg does that part. I'll land it today.

**Comment by ashleygwilliams** [comment]
awesome! thanks for the quick reply @jasnell :) i'll share with the group at our meeting today

**Comment by jasnell** [comment]
Landed in ea9a396c

**Comment by ashleygwilliams** [comment]
:tada: yay!

**Comment by Fishrock123** [comment]
Rod is away this week, maybe @jbergstroem can do it.

**Comment by rvagg** [comment]
```
1 route(s) to add
0 route(s) to remove
Adding inclusivity -> ashley666ashley@gmail.com, julie.pagano@gmail.com, beau@beaugunderson.com, nathan@nathan7.eu, bryan@theoreticalideations.com, forrest@npmjs.com, jona@jona.io, thechargingvolcano@gmail.com, rtrott@gmail.com, node@sykosomatic.org...
``

This is active for @iojs.org now, I'll have to contact the LF helpdesk to make an @nodejs.org alias, I'll let you know when they've completed their bit.

**Comment by ashleygwilliams** [comment]
awesome ya'll! thanks so much for keeping this moving :)

**Comment by rvagg** [comment]
@nodejs/build FYI the process here on @nodejs.org aliases is that you have to contact the LF helpdesk and/or @mikeal who I think has admin access to the Google Apps account for @nodejs.org now. In the past they have been fairly responsive to simple requests like this.

**Comment by rvagg** [comment]
alias was added to @nodejs.org and a test email was sent, hopefully y'all got that and can confirm it's working.

**Pull request closed without merging**
