### PR TITLE
Update Geoffrey emails

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
Updating the email lists with my email addresses. We’ll find out if our scripts support `+` characters in email addresses.

### CODE REVIEW

**Comment by Trott** [comment]
Can you please add yourself to `crypto-export` as well?

**Review by richardlau — APPROVED** [review]

**Review by BridgeAR — APPROVED** [review]

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
@mhdawson

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by richardlau** [comment]
deployed

**Pull request merged**
