### PR TITLE
add new ctc members to ctc@iojs.org

### PR DESCRIPTION
**Pull request by rvagg**
also sorted by username so it matches the READMEs

@nodejs/ctc

### CODE REVIEW

**Comment by orangemocha** [comment]
lgtm

**Comment by rvagg** [comment]
done, thanks

**Comment by rvagg** [comment]
@trott, @evanlucas, @ofrobots, @chalker I'm sending an email to the list, let me know if you're not getting it.

**Comment by ChALkeR** [comment]
@rvagg, I didn't receive it (yet?).

**Comment by rvagg** [comment]
sorry, ended up writing more than I expected, check now

**Comment by ChALkeR** [comment]
@rvagg Yes, I received it, thanks! =)

**Comment by evanlucas** [comment]
I got it too. Thanks

**Pull request merged**
