### PR TITLE
Inclusivity update

### PR DESCRIPTION
**Pull request by nebrius**
Updated the inclusivity members to reflect latest membership changes

### CODE REVIEW

**Comment by beaugunderson** [comment]
LGTM

**Comment by nebrius** [comment]
Can we let this sit another day or two before merging?

**Comment by nebrius** [comment]
I think this is ready to land now, things seem to have settled. If this looks good, can we go ahead and merge it?

**Comment by jbergstroem** [comment]
Ok, will merge.

**Comment by jbergstroem** [comment]
Merged (and pushed) in 267fa4079271a054d32178ab3f9ec13f9d04b3a9.

**Comment by nebrius** [comment]
Thank you @jbergstroem

**Pull request closed without merging**
