### PR TITLE
add Michael Dawson to CTC mailing list

### PR DESCRIPTION
**Pull request by Trott**
/cc @mhdawson @rvagg

### CODE REVIEW

**Comment by jbergstroem** [comment]
LGTM

**Comment by TheAlphaNerd** [comment]
lgtm

**Comment by mhdawson** [comment]
LGTM :)

**Comment by Trott** [comment]
I imagine there's a process here and someone with the right privileges or API key or whatever will have to do something with this for it to actually take effect?

**Comment by jbergstroem** [comment]
I'll update once landed.

**Comment by jbergstroem** [comment]
(updated a few hours ago)

**Pull request merged**
