### PR TITLE
Add alias for user-feedback

### PR DESCRIPTION
**Pull request by mhdawson**
Initial alias entries.

See https://github.com/nodejs/user-feedback/issues/12 for
context.

### CODE REVIEW

**Comment by Trott** [comment]
Probably should be `feedback` rather than `user-feedback`? (Who else are you expecting feedback from and will `user-feedback` dissuade them?)

**Comment by mhdawson** [comment]
@Trott  what do you think of `end-user-feedback` as this is for a specific context, not just feedback of all types.

**Comment by Trott** [comment]
`end-user-feedback` sounds like you want feedback from people using Node.js applications, not people writing and/or hosting them. I think `end-user-feedback` might be *less* clear than `user-feedback`. That said, I won't object to it if others love it.

How about `developer-feedback`?

**Comment by Trott** [comment]
Although, I still think just `feedback` is the best. Again, who are you trying to discourage by making it more specific than that?

**Comment by mhdawson** [comment]
I really just wanted an email were people can send us their contact info without having to make it public.  The team is actually called user-feedback (as is the repo https://github.com/nodejs/user-feedback) so user-feedback as the email alias went along with that.  

There is no plan to monitor it/respond to general feedback so I want to avoid that impression.

Maybe user-feedback-team ?

**Comment by Trott** [comment]
> I really just wanted an email were people can send us their contact info without having to make it public.

Just go with `user-feedback` and ignore me. If people start using it in ways for which it is not intended, you can always change it later or remove it or whatever.

**Comment by Trott** [comment]
(And yeah, `user-feedback-team` is fine too if you prefer that. Whichever/whatever.)

**Comment by mhdawson** [comment]
@Trott thanks, I'll just stick to user-feedback as Rod already had the user-feedback alias setup to to point to it.

**Comment by mhdawson** [comment]
Landed as 23ddf939047491e5d3fae69cae5151bce5ff1247

**Pull request closed without merging**
