### PR TITLE
email: add Stefan Stojanovic to build aliases

### PR DESCRIPTION
**Pull request by joaocgreis**
Ref: https://github.com/nodejs/build/pull/3726

### CODE REVIEW

**Review by UlisesGascon — APPROVED** [review]

**Comment by UlisesGascon** [comment]
Just a minor note: this should be applied after https://github.com/nodejs/build/pull/3726 got merged.

**Review by richardlau — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by StefanStojanovic — APPROVED** [review]

**Comment by joaocgreis** [comment]
https://github.com/nodejs/build/pull/3726 was merged, so this can land now.

**Comment by mhdawson** [comment]
deployed.

**Pull request merged**
