### PR TITLE
email: add lts email alias

### PR DESCRIPTION
**Pull request by jasnell**
Add `lts@iojs.org` alias

/cc @nodejs/lts

### CODE REVIEW

**Comment by rvagg** [comment]
what's the purpose of this one?

**Comment by jasnell** [comment]
To make it easier to send out meeting reminders/updates, etc. Not for general discussion

**Comment by jasnell** [comment]
I'd consider it optional, really. not critical for it to land

**Comment by bnoordhuis** [comment]
LGTM.  Handy for sending out invites, amirite?

**Comment by rvagg** [comment]
Invites for calendars are usually better when people are added individually but also possible to do on a list.

My concern here is precedent, do we mind if each WG ends up with its own email address? Perhaps not but let's think through possible ramifications.

**Comment by jasnell** [comment]
No worries on holding off. I created a small command line tool that
generates a list of emails for nodejs team members that meets my needs for
now!

**Comment by jasnell** [comment]
We don't actually need this. It's more of a convenience. Going to close and withdraw this.

**Pull request closed without merging**
