### PR TITLE
ci-alert: add phillipj

### PR DESCRIPTION
**Pull request by jbergstroem**
@phillipj likes emails as much as the rest of us.

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
I'd be in for getting some more emails too if it would be considered usefull

**Comment by jbergstroem** [comment]
@TheAlphaNerd it's basically notifications for when slaves changes status (offline/online). Still interested?

**Comment by Starefossen** [comment]
giphy

(sorry, had to)

But be advised that this sends out 5-6 emails a day on average about Jenkins slaves going offline/online.

**Comment by jbergstroem** [comment]
@phillipj ping!

**Comment by phillipj** [comment]
Woopsie, yepp this LGTM! Can't wait to get my inbox filled 🎆

**Comment by jbergstroem** [comment]
Updated!

**Pull request merged**
