### PR TITLE
add inclusivity wg emails to the report alias

### PR DESCRIPTION
**Pull request by sup**
in order to progress further with #9

### CODE REVIEW

**Comment by jasnell** [comment]
I thought the intent was to keep the `inclusivity@` alias separate from the `report@` alias (See: https://github.com/nodejs/email/issues/9#issuecomment-159677264).

**Comment by sup** [comment]
whoops. i suppose i'll forwards emails to `report@` to `inclusivity@` which will contain all members' emails

**Comment by rvagg** [comment]
-1 from me for now. Two problems I see: (a) "inclusivity" is not yet ratified as an actual WG and (b) I don't see details on what the intent of the `report@nodejs.org` address is—where it will be used and what will be said in conjunction with its suggested use. We have governance structures in place and they don't _currently_ include a reporting mechanism that involves individuals outside of those structures.

**Comment by jasnell** [comment]
See: https://github.com/nodejs/TSC/pull/16

**Comment by jasnell** [comment]
I'm -1 on this also. Use of the `report@nodejs.org` alias is intended for use under the proposed moderation policy (https://github.com/nodejs/TSC/pull/16). The Inclusivity WG is expected to adopt it's own moderation policy and CoC (from what I understand). The original intent of the `inclusivity@nodejs.org` alias, I believe, is to give that WG it's own address for reporting issues. It would not be appropriate to forward `report@nodejs.org` notes to `inclusivity@nodejs.org`.

**Comment by sup** [comment]
alright, i'm closing this then. thanks for your feedback.

**Pull request closed without merging**
