### PR TITLE
add gabrielschulhof to TSC

### PR DESCRIPTION
**Pull request by Trott**
/ping @nodejs/tsc

### CODE REVIEW

**Comment by MylesBorins** [comment]
Want to confirm this email is correct and working, I just attempted to email and got a delivery failure. Please dismiss this review if everything is fine

**Comment by mhdawson** [comment]
Strange that is the email I've used to contact him in the past as well. Will try to validate.

**Comment by mhdawson** [comment]
I sent email to Gabriel using the address and he responded back so I believe it is ok. Going to dismiss Myles  review since he said it was ok and land.

**Comment by mhdawson** [comment]
Should be live now.

**Pull request merged**
